compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
    '@typescript-eslint/parser@*':
        dependencies:
            typescript: '*'
    '@typescript-eslint/typescript-estree@*':
        dependencies:
            typescript: '*'
    eslint-module-utils@*:
        dependencies:
            typescript: '*'

yarnPath: .yarn/releases/yarn-4.6.0.cjs
