import { defineConfig } from 'oxfmt'

export default defineConfig({
    printWidth: 120,
    singleQuote: true,
    trailingComma: 'es5',
    bracketSpacing: true,
    semi: false,
    tabWidth: 4,
    endOfLine: 'lf',
    // Prettier did not reorder package.json keys; flip to `true` to opt in.
    sortPackageJson: true,
    ignorePatterns: [
        // Yarn-generated files; not ours to format.
        '.yarn/**',
        '.pnp.*',
        // Generated by release-please.
        '**/CHANGELOG.md',
    ],
})
