name: Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install --workspace=immer-yjs
      - name: Build
        run: npm run build --workspace=immer-yjs
      - name: Copy README into the workspace
        run: cp README.md packages/immer-yjs/
      - name: Publish to NPM
        run: npm publish --access public --workspace=immer-yjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
