name: Tests
on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    name: Code Inspection
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: yarn install --immutable
      - name: Check Code Formatting
        run: yarn check:formatting
      - name: Check Types
        run: yarn check:types
      #        No linters for this repo (yet)
      #      - name: Lint
      #        run: |
      #          yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Test Build Output
        run: yarn build
